# Generated by Django 5.0.1 on 2024-01-16 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_part",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[django.core.validators.MinLengthValidator(15)],
            ),
        ),
    ]
