# Generated by Django 5.0.1 on 2024-01-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0002_alter_shorturl_short_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="qr",
            field=models.ImageField(blank=True, null=True, upload_to="qr/"),
        ),
    ]
