# Generated by Django 5.0.1 on 2024-01-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0003_shorturl_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="short_url",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
