# Generated by Django 5.0.1 on 2024-01-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0005_shorturl_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_part",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
